# Generated by Django 3.2.5 on 2022-04-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('hotel_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Hotel ID')),
                ('hotel_name', models.CharField(max_length=200, verbose_name='Hotel Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Logical Delete')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'db_table': 'tb_hotel',
            },
        ),
    ]
